api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from .views import *

urlpatterns = [

    # # register a user
    # url(r'register/user',RegisterUserView.as_view({'post': 'create_user'})),
    # url(r'verify/user', RegisterUserView.as_view({'post': 'verify_user'})),
    #
    # # login and logout handlers
    # url(r'login/user/', LoginView.as_view({'post': 'login_user'})),
    # url(r'logout/user/', LogoutView.as_view({'post': 'logout_user'})),
    #
    # # product urls
    # url(r'create/product', ProductView.as_view({'post': 'create_prouct'})),
    # url(r'list/products', ProductView.as_view({'get': 'get_product_listing'})),
    # url(r'list/child/products/(?P<id>\d+)', ProductView.as_view({'get': 'get_child_products'})),
    # url(r'update/products', ProductView.as_view({'post': 'update_products'})),
    #
    # # gradeproduct
    # url(r'create/gradeproducts/(?P<product_pk>\d+)', GradeProductView.as_view({'post': 'create_grade_product'})),
    # url(r'list/gradeproducts', GradeProductView.as_view({'get': 'get_grade_product_listing'})),
    # url(r'update/gradeproduct/(?P<grade_product_pk>\d+)', GradeProductView.as_view({'post': 'update_grade_product'})),
    #
    #
    # # stock related functionality
    # url(r'create/stock_posting', StockView.as_view({'post': 'create_stock_posting'})),
    # url(r'get/stock_posting/listing/(?P<grade_product_id>\d+)/(?P<page_number>\d+)', StockView.as_view({'get': 'get_stock_list'})),
    # url(r'get/stock_posting/details/(?P<posting_pk>\d+)', StockView.as_view({'get': 'get_stock_detail'})),
    # url(r'update/stock_posting/(?P<posting_pk>\d+)', StockView.as_view({'post': 'update_stock_posting'})),
    # url(r'delete/stock_posting/(?P<posting_pk>\d+)', StockView.as_view({'delete': 'delete_stock_posting'})),
    #
    # # update order API
    # url(r'create/order', OrderView.as_view({'post': 'create_order'})),
    # url(r'update/order', OrderView.as_view({'post': 'update_order'})),
    # url(r'get/order/(?P<order_id>\d+)', OrderView.as_view({'get': 'get_order_status'})),
    #
    #
    # # UserProfile View
    # url(r'get/profile', UserProfileView.as_view({'get': 'get_userprofile'})),
    # url(r'update/profile', UserProfileView.as_view({'post': 'update_profile'})),

    # Search Company
    url(r'search_company', CompanySearchViewApi.as_view(), name="get_company_list"),
]

test_sub/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^web/', include('web.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^$', RedirectView.as_view(url='web/landing/')),
    # url(r'^api/', include('web.rest_urls'))
]

web/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from core.models import CompanyModel, UserProfile
from pprint import pprint

class BaseForm(forms.Form):
    """Base form for all the forms in EMS"""
    def is_phone_no_invalid(self, phone_number):
        """ Util function for validating phone number """
        return ((not str(phone_number).isdigit()) or (len(phone_number)!=10))

    def is_name_invalid(self,name):
        """
        This function return true if name contains any digit. However it fails to address the special characters.
        """
        return self.has_numbers(name)

    def user_email_already_exists(self, email):
        """
        This function return true if the user email provided already exists in database.
        """
        return User.objects.filter(email=email).exists()

    def company_email_already_exists(self, email):
        """
        This function return true if the company email provided already exists in database.
        """
        return CompanyModel.objects.filter(company_email=email).exists()

    def user_phone_no_already_exists(self, phone_no):
        """
        This function return true if the Phone Number by user provided already exists in user's database.
        """
        return UserProfile.objects.filter(phone_no=phone_no).exists()

    def company_phone_no_already_exists(self, phone_no):
        """
        This function return true if the Phone Number by user provided already exists in user's database.
        """
        return CompanyModel.objects.filter(company_phone_no=phone_no).exists()

    def has_numbers(self,inputString):
        """This function to to check if """
        return any(char.isdigit() for char in inputString)


class CreateUserAndCompanyForm(BaseForm):
    """Form for user registration/creating account"""


    # USER #
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'))


    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length= 30)
    gender = forms.ChoiceField(choices=GENDER_CHOICES)
    dob = forms.DateField()
    user_email = forms.EmailField()
    user_phone_no = forms.CharField(max_length=10)
    password = forms.CharField(max_length = 50)
    confirm_password = forms.CharField(max_length=50)


    # COMPANY #
    WHERE_YOU_HEARD_ABT_US_CHOICES = (
        ('B', 'Blog'),
        ('W', 'Website'),
        ('A', 'Advertisement'),
        ('S', 'Social Media'),
        ('O', 'Other'),)
    company_name = forms.CharField(max_length=150)
    company_email = forms.CharField(max_length=150)
    company_phone_no = forms.CharField(max_length=10)
    ad_reference = forms.ChoiceField(choices=WHERE_YOU_HEARD_ABT_US_CHOICES)


    def clean(self, *args, **kwargs):
        """Clean function"""

        cleaned_data = super(CreateUserAndCompanyForm, self).clean()

        # USER #
        if self.is_name_invalid(cleaned_data.get('first_name')):
            raise forms.ValidationError('First Name you have entered is invalid')

        if self.is_name_invalid(cleaned_data.get('last_name')):
            raise forms.ValidationError('Last Name you have entered is invalid')

        if self.user_email_already_exists(cleaned_data.get('user_email')):
            raise forms.ValidationError('User Email Id provided already exists in database. Use different Email Id')

        if self.is_phone_no_invalid(cleaned_data['user_phone_no']):
            raise forms.ValidationError('The user phone number provided is invalid')

        if self.user_email_already_exists(cleaned_data['user_phone_no']):
            raise forms.ValidationError('The user phone number provided already exist in the database')

        if cleaned_data.get('password') != cleaned_data.get('confirm_password'):
            raise forms.ValidationError('Passwords cannot be different')

        if len(cleaned_data.get('password')) < 8:
            raise forms.ValidationError('Password must contain at least 8 characters')

        # COMPANY #
        if self.company_email_already_exists(cleaned_data['company_email']):
            raise forms.ValidationError('Company Email Id provided already exists in database. Use different Email Id')


        if self.is_phone_no_invalid(cleaned_data['company_phone_no']):
            raise forms.ValidationError('The Company phone number provided is invalid')

        if self.company_phone_no_already_exists(cleaned_data['company_phone_no']):
            raise forms.ValidationError('The Company phone number provided already exist in database')

        else:
            return cleaned_data


class CreateUserForm(BaseForm):
    """Form for user registration/creating account"""
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'))


    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length= 30)
    gender = forms.ChoiceField(choices=GENDER_CHOICES)
    dob = forms.DateField()
    user_email = forms.EmailField()
    user_phone_no = forms.CharField(max_length=10)
    password = forms.CharField(max_length = 50)
    confirm_password = forms.CharField(max_length=50)


    def clean(self, *args, **kwargs):
        """Clean function"""

        cleaned_data = super(CreateUserForm, self).clean()

        if self.is_name_invalid(cleaned_data.get('first_name')):
            raise forms.ValidationError('First Name you have entered is invalid')

        if self.is_name_invalid(cleaned_data.get('last_name')):
            raise forms.ValidationError('Last Name you have entered is invalid')

        if self.user_email_already_exists(cleaned_data.get('email')):
            raise forms.ValidationError('Email Id provided already exists in database. Use different Email Id')

        if self.is_phone_no_invalid(cleaned_data['user_phone_no']):
            raise forms.ValidationError('The user phone number provided is invalid')

        if cleaned_data.get('password') != cleaned_data.get('confirm_password'):
            raise forms.ValidationError('Passwords cannot be different')

        if len(cleaned_data.get('password')) < 8:
            raise forms.ValidationError('Password must contain at least 8 characters')
        else:
            return cleaned_data

class CreateCompanyForm(BaseForm):
    """ Form to create company """
    WHERE_YOU_HEARD_ABT_US_CHOICES = (
        ('B', 'Blog'),
        ('W', 'Website'),
        ('A', 'Advertisement'),
        ('S', 'Social Media'),
        ('O', 'Other'),)

    company_name = forms.CharField(max_length=150)
    company_email = forms.CharField(max_length=150)
    company_phone_no = forms.CharField(max_length=10)
    where_heard_abt_us = forms.ChoiceField(choices=WHERE_YOU_HEARD_ABT_US_CHOICES)

    def clean(self, *args, **kwargs):
        """Clean function"""
        cleaned_data = super(CreateCompanyForm, self).clean()

        pprint(cleaned_data)

        if self.company_email_already_exists(cleaned_data['company_email']):
            raise forms.ValidationError('Email Id provided already exists in database. Use different Email Id')
        if self.is_phone_no_invalid(cleaned_data['company_phone_no']):
            raise forms.ValidationError('The Company phone number provided is invalid')
        if self.company_phone_no_already_exists(cleaned_data['company_phone_no']):
            raise forms.ValidationError('The Company phone number provided already exist in database')
        else:
            return cleaned_data

#### Free Subscription Form ####

class FreeFieldForm(BaseForm):
    """Form to input the free subscription fields for a company """
    address = forms.CharField(max_length=120, label="Address Line 1:", required=False)
    city = forms.CharField(max_length=30, label="City:", required=False)
    pin = forms.CharField(max_length=6, label="pin", required=False)
    website = forms.CharField(max_length=200, label="Company website:", required=False)
    year_founded = forms.CharField(max_length=4, label="Year Founded:", required=False)
    about = forms.CharField(max_length=100, label="About Company:", required=False)

#### Free Subscription Form ####



#### Premium Subscription Form ####

class BasicPremiumFieldForm(BaseForm):
    """ Form to save the basic premium fields of the company"""
    logo = forms.ImageField(required=False, label="Company logo:")
    registration_no = forms.CharField(max_length=12, label="Company registration No:", required=False)
    bio = forms.CharField(max_length=1000, label="Company bio:", required=False)
    no_of_emp = forms.IntegerField(required=False, label="No of employee:")
    sale_volume = forms.CharField(max_length=30, label="Sale volume:", required=False)

class GalleryForm(BaseForm):
    """Form for the images of gallary of the company"""
    image = forms.ImageField(required=False, label="Image:")

class BrochureForm(BaseForm):
    """Form for the brochures of the company """
    brochure = forms.FileField(required=False, label="Company Brochure:")

class VideoLinkForm(BaseForm):
    """Form for the video link of the company"""
    video_link = forms.URLField(label="video_link:", required=False)

class KeyClient(BaseForm):
    """Form for the key clients of the company"""
    key_client = forms.CharField(max_length=150, label="Key Client:")

# class KeyAlliance(BaseModel):


class LocationForm(BaseForm):
    """Form to save the different locations of the company"""
    location_type = forms.CharField(max_length=30, label="Location Type:", required=False)
    location = forms.CharField(max_length=200, label="Location:", required=False)

class CertificationForm(BaseForm):
    """Form for the different certificates of company"""
    certi_name = forms.CharField(max_length=100, label="Certification name:", required=False)
    certi_description = forms.CharField(max_length=200, label="Certificatio description:", required=False)

templates/add_company.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}

<div class="container">

    <h1 class="text-center">Company Detail</h1>
    <div class="col-md-offset-3 col-md-6">

        {% if error %}
        {% for errors in error %}
        <p class="text-danger">{{ errors }}</p>
        {% endfor %}
        {% endif %}

        <form class="form-login custom-form-login" method="post" action="/web/add_company/" enctype="multipart/form-data">

            {% csrf_token %}

            <div class="form-group">
                <label for="company_name">Company Name:</label>
                {{ form.company_name|attr:"class:form-control"|attr:"id:company_name"|attr:"type:text"|attr:"style:text-transform:uppercase"|attr:"required:true"|attr:"autocomplete:off" }}
            </div>
            <div class="form-group">
                <label for="id_where_heard_abt_us">Where you heard about us ?:</label><br>
                {{ form.where_heard_abt_us|attr:"class:form-control"|attr:"autocomplete:off"}}

            </div>
            <div class="form-group">
                <label for="company_email">Company Email:</label><br>
                {{ form.company_email|attr:"class:form-control"|attr:"type:email"|attr:"required:true"|attr:"autocomplete:off" }}
            </div>

            <div class="form-group">
                <label for="id_company_phone_no">Company Phone No (XXXXXXXXXX):</label>
                {{ form.company_phone_no|attr:"class:form-control"|attr:"required:true"|attr:"autocomplete:off"|attr:"type:text"|attr:"maxlength:10"|attr:"pattern:[789][0-9]{9}"|attr:"title:The given phone number is not valid indian mobile no."}}
            </div>
            <div id="lower text-center">
                <br>
                <button class="btn ladda-button btn-theme btn-block" data-style="slide-right" style="color: #2A3542"><span class="ladda-label">Submit</span></button>
            </div>
            <br><br>

            <div class="text-center">
                Already Registered ?<br/>
                <p ><a href="/">Click Here to Login</a></p>
            </div>
            {% csrf_token %}
        </form>

    </div>
    {% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Oil and Gas</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="/static/js.cookie.js"></script> <!-- To be deleted along with the js file-->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-3-typeahead/4.0.1/bootstrap3-typeahead.min.js"></script>

</head>
<body>
{% block content %}
This is the main content of the project.
{% endblock content %}
</body>
</html>

templates/create_user_and_claim_company.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}

<div class="container">

    <div class="row">
        <div class="col-md-offset-3 col-md-6 ">

            <h3 class="text-center">Claim Your Company</h3>


            <form id="form"  action="/web/create_user_and_claim_company/" method="post" enctype="multipart/form-data" >

                {% if error %}
                {% for errors in error %}
                <p class="text-danger">{{ errors }}</p>
                {% endfor %}
                {% endif %}
                {% csrf_token %}

                <div class="form-group text-center">

                    <label for="company_name">Select The Company Name:</label>
                    <input class="form-control" type="text" name="company_name" id="company_name" autocomplete="off" />
                    <br>
                    <a href="/web/create_user_and_company">Register your company is it not present in the link</a>
                    <div id="user_form">

                        <div class="col-md-offset-3 col-md-8">
                            <h3 class="text-center">User Details</h3>

                            {% csrf_token %}

                            <div class="form-group">
                                <label for="first_name">First Name:</label>
                                {{ user_form.first_name|attr:"class:form-control"|attr:"id:first_name"|attr:"type:text"|attr:"style:text-transform:uppercase"|attr:"required:true"|attr:"autocomplete:off" }}
                            </div>

                            <div class="form-group">
                                <label for="last_name">Last Name:</label>
                                {{ user_form.last_name|attr:"class:form-control"|attr:"id:last_name"|attr:"type:text"|attr:"style:text-transform:uppercase"|attr:"required:true"|attr:"autocomplete:off" }}
                            </div>

                            <div class="form-group">
                                <label for="id_gender">Gender:</label>
                                {{ user_form.gender|attr:"class:form-control"|attr:"required:true"|attr:"autocomplete:off"}}
                            </div>

                            <div class="form-group">
                                <label for="id_dob">Date of birth:</label>
                                {{user_form.dob|attr:"class:form-control"|attr:"type:date"|attr:"required:true"|attr:"autocomplete:off"}}
                            </div>

                            <div class="form-group">
                                <label for="user_email">User Email:</label><br>
                                {{ user_form.user_email|attr:"class:form-control"|attr:"type:email"|attr:"required:true"|attr:"autocomplete:off" }}
                            </div>

                            <div class="form-group">
                                <label for="id_user_phone_no">User Phone No (XXXXXXXXXX):</label>
                                {{ user_form.user_phone_no|attr:"class:form-control"|attr:"required:true"|attr:"autocomplete:off"|attr:"type:text"|attr:"maxlength:10"|attr:"pattern:[789][0-9]{9}"|attr:"title:The given phone number is not valid indian mobile no."}}
                            </div>

                            <div class="form-group">
                                <label for="password">Password:</label>
                                {{ user_form.password|attr:"class:form-control"|attr:"type:password"|attr:"required:true"|attr:"autocomplete:off" }}
                            </div>


                            <div class="form-group">
                                <label for="password">Confirm Password:</label>
                                {{ user_form.confirm_password|attr:"class:form-control"|attr:"type:password"|attr:"required:true"|attr:"autocomplete:off" }}

                            </div>

                            <div id="lower text-center">
                                <br>
                                <button class="btn ladda-button btn-theme btn-block" data-style="slide-right" style="color: #2A3542"><span class="ladda-label">Submit</span></button>
                            </div>
                            <br><br>

                            <div class="text-center">
                                Already Registered ?<br/>
                                <p ><a href="/">Click Here to Login</a></p>
                            </div>
                            {% csrf_token %}


                        </div>
                    </div>


            </form>
        </div>
    </div>




    {% block custom_script %}

    <script>
                    document.getElementById("user_form").style.visibility = 'hidden';
                    $(document).ready(function () {
                        $("#company_name").keypress(function () {
                            var value_l = $("#company_name").val();
                            if (value_l.length >= 1) {
                                $.get("/web/get_company", function (data) {
                                    var $input = $('#company_name');
                                    $input.typeahead({
                                        source: data, autoSelect: false, displayText: function (item) {
                                            return item;
                                        }, afterSelect: function (current) {

                                            document.getElementById("user_form").style.visibility = 'visible';
                                            document.getElementById("company_name").readOnly = true;
                                            // document.getElementById("company_name").disabled = true;

                                        }
                                    });
                                }, 'json');
                            }
                        });
                    });
                </script>

    {% endblock %}
    {% endblock content %}
    </body>
    </html>

templates/create_user_and_company.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}

<div class="container">

    <h1 class="text-center">User and Company Details</h1>
    <div class="col-md-offset-3 col-md-6">

        {% if error %}
        {% for errors in error %}
        <p class="text-danger">{{ errors }}</p>
        {% endfor %}
        {% endif %}

        <form class="form-login custom-form-login" method="post" action="/web/create_user_and_company/" enctype="multipart/form-data">

            {% csrf_token %}

            <div class="form-group">
                <label for="first_name">First Name:</label>
                {{ form.first_name|attr:"class:form-control"|attr:"id:first_name"|attr:"type:text"|attr:"style:text-transform:uppercase"|attr:"required:true"|attr:"autocomplete:off" }}
            </div>

            <div class="form-group">
                <label for="last_name">Last Name:</label>
                {{ form.last_name|attr:"class:form-control"|attr:"id:last_name"|attr:"type:text"|attr:"style:text-transform:uppercase"|attr:"required:true"|attr:"autocomplete:off" }}
            </div>

            <div class="form-group">
                <label for="id_gender">Gender:</label>
                {{ form.gender|attr:"class:form-control"|attr:"required:true"|attr:"autocomplete:off"}}
            </div>

            <div class="form-group">
                <label for="id_dob">Date of birth:</label>
                {{form.dob|attr:"class:form-control"|attr:"type:date"|attr:"required:true"|attr:"autocomplete:off"}}
            </div>

            <div class="form-group">
                <label for="user_email">User Email:</label><br>
                {{ form.user_email|attr:"class:form-control"|attr:"type:email"|attr:"required:true"|attr:"autocomplete:off" }}
            </div>

            <div class="form-group">
                <label for="id_user_phone_no">User Phone No (XXXXXXXXXX):</label>
                {{ form.user_phone_no|attr:"class:form-control"|attr:"required:true"|attr:"autocomplete:off"|attr:"type:text"|attr:"maxlength:10"|attr:"pattern:[789][0-9]{9}"|attr:"title:The given phone number is not valid indian mobile no."}}
            </div>

            <div class="form-group">
                <label for="password">Password:</label>
                {{ form.password|attr:"class:form-control"|attr:"type:password"|attr:"required:true"|attr:"autocomplete:off" }}
            </div>


            <div class="form-group">
                <label for="password">Confirm Password:</label>
                {{ form.confirm_password|attr:"class:form-control"|attr:"type:password"|attr:"required:true"|attr:"autocomplete:off" }}

            </div>


            <br><hr><hr><br>


            <div class="form-group">
                <label for="company_name">Company Name:</label>
                {{ form.company_name|attr:"class:form-control"|attr:"id:company_name"|attr:"type:text"|attr:"style:text-transform:uppercase"|attr:"required:true"|attr:"autocomplete:off" }}
            </div>
            <div class="form-group">
                <label for="id_where_heard_abt_us">Where you heard about us ?:</label><br>
                {{ form.ad_reference|attr:"class:form-control"|attr:"autocomplete:off"}}

            </div>
            <div class="form-group">
                <label for="company_email">Company Email:</label><br>
                {{ form.company_email|attr:"class:form-control"|attr:"type:email"|attr:"required:true"|attr:"autocomplete:off" }}
            </div>

            <div class="form-group">
                <label for="id_company_phone_no">Company Phone No (XXXXXXXXXX):</label>
                {{ form.company_phone_no|attr:"class:form-control"|attr:"required:true"|attr:"autocomplete:off"|attr:"type:text"|attr:"maxlength:10"|attr:"pattern:[789][0-9]{9}"|attr:"title:The given phone number is not valid indian mobile no."}}
            </div>
            <div id="lower text-center">
                <br>
                <button class="btn ladda-button btn-theme btn-block" data-style="slide-right" style="color: #2A3542"><span class="ladda-label">Submit</span></button>
            </div>
            <br><br>

            <div class="text-center">
                Already Registered ?<br/>
                <p ><a href="/web/login/">Click Here to Login</a></p>
            </div>
            {% csrf_token %}
        </form>

    </div>
    {% endblock %}

templates/dashboard.html
{% extends "base.html" %}
{% load widget_tweaks %}



{% block content %}

<hi>This is Dashboard page</h1>
<br><br>

{% if message %}
<p style="color:green; font-size:125%">{{ message }}</p>
{% endif %}

{% if error %}
<p style="color:red; font-size:125%">{{ error }}</p>
{% endif %}

<br><br>
<a href="/web/logout">Logout</a><br><br>
<a href="/web/dashboard">Dashboard</a><br><br><br><br>
<a href="/web/free_field">Free Fields</a><br><br><br><br>
<h1>Premium Fields</h1><br><br>
<a href="/web/basic_premium_field">Basic Premium Fields</a><br><br>
<a href="/web/gallery">Click To add Gallery Images</a><br><br>

<a href="/web/brochure">Click add Brochure Brochure</a><br><br>
<a href="/web/video_link">Click To Add Video Link</a><br><br>
<a href="/web/location">Click to add you different Locations</a><br><br>
<a href="/web/certification">Click to add your certifications</a><br><br>
<a href="/web/social_link">Click to Add your social Links</a><br><br>


{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load widget_tweaks %}



{% block content %}

<hi>This is home page</h1>

{% endblock %}

templates/register.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}

<div class="container">

    <h1 class="text-center">User and Company Details</h1>
    <div class="col-md-offset-3 col-md-6">

        {% if error %}
        {% for errors in error %}
        <p class="text-danger">{{ errors }}</p>
        {% endfor %}
        {% endif %}

        <form class="form-login custom-form-login" method="post" action="/web/register/" enctype="multipart/form-data">

            {% csrf_token %}

            <div class="form-group">
                <label for="first_name">First Name:</label>
                {{ form.first_name|attr:"class:form-control"|attr:"id:first_name"|attr:"type:text"|attr:"style:text-transform:uppercase"|attr:"required:true"|attr:"autocomplete:off" }}
            </div>

            <div class="form-group">
                <label for="last_name">Last Name:</label>
                {{ form.last_name|attr:"class:form-control"|attr:"id:last_name"|attr:"type:text"|attr:"style:text-transform:uppercase"|attr:"required:true"|attr:"autocomplete:off" }}
            </div>

            <div class="form-group">
                <label for="id_gender">Gender:</label>
                {{ form.gender|attr:"class:form-control"|attr:"required:true"|attr:"autocomplete:off"}}
            </div>

            <div class="form-group">
                <label for="id_dob">Date of birth:</label>
                {{form.dob|attr:"class:form-control"|attr:"type:date"|attr:"required:true"|attr:"autocomplete:off"}}
            </div>

            <div class="form-group">
                <label for="user_email">User Email:</label><br>
                {{ form.user_email|attr:"class:form-control"|attr:"type:email"|attr:"required:true"|attr:"autocomplete:off" }}
            </div>

            <div class="form-group">
                <label for="id_user_phone_no">User Phone No (XXXXXXXXXX):</label>
                {{ form.user_phone_no|attr:"class:form-control"|attr:"required:true"|attr:"autocomplete:off"|attr:"type:text"|attr:"maxlength:10"|attr:"pattern:[789][0-9]{9}"|attr:"title:The given phone number is not valid indian mobile no."}}
            </div>

            <div class="form-group">
                <label for="password">Password:</label>
                {{ form.password|attr:"class:form-control"|attr:"type:password"|attr:"required:true"|attr:"autocomplete:off" }}
            </div>


            <div class="form-group">
                <label for="password">Confirm Password:</label>
                {{ form.confirm_password|attr:"class:form-control"|attr:"type:password"|attr:"required:true"|attr:"autocomplete:off" }}
                
            </div>


            <br><hr><hr><br>


            <div class="form-group">
                <label for="company_name">Company Name:</label>
                {{ form.company_name|attr:"class:form-control"|attr:"id:company_name"|attr:"type:text"|attr:"style:text-transform:uppercase"|attr:"required:true"|attr:"autocomplete:off" }}
            </div>
            <div class="form-group">
                <label for="id_where_heard_abt_us">Where you heard about us ?:</label><br>
                {{ form.ad_reference|attr:"class:form-control"|attr:"autocomplete:off"}}

            </div>
            <div class="form-group">
                <label for="company_email">Company Email:</label><br>
                {{ form.company_email|attr:"class:form-control"|attr:"type:email"|attr:"required:true"|attr:"autocomplete:off" }}
            </div>

            <div class="form-group">
                <label for="id_company_phone_no">Company Phone No (XXXXXXXXXX):</label>
                {{ form.company_phone_no|attr:"class:form-control"|attr:"required:true"|attr:"autocomplete:off"|attr:"type:text"|attr:"maxlength:10"|attr:"pattern:[789][0-9]{9}"|attr:"title:The given phone number is not valid indian mobile no."}}
            </div>
            <div id="lower text-center">
                <br>
                <button class="btn ladda-button btn-theme btn-block" data-style="slide-right" style="color: #2A3542"><span class="ladda-label">Submit</span></button>
            </div>
            <br><br>

            <div class="text-center">
                Already Registered ?<br/>
                <p ><a href="/">Click Here to Login</a></p>
            </div>
            {% csrf_token %}
        </form>

    </div>
    {% endblock %}